#!/bin/bash
rm -rf *.tar
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- distclean
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- orangepi5_defconfig 
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j16 tar-pkg
./mkupdatepkg

exit 0 

